DROP TABLE IF EXISTS christmas_elf CASCADE;

CREATE TABLE christmas_elf (
id INTEGER generated by default as identity, 
age INTEGER, 
best_toy VARCHAR(255), 
favourite_food VARCHAR(255), 
height DOUBLE, 
is_nice BOOLEAN not null, 
name VARCHAR(255), 
primary key (id))